#/employees:
  displayName: Employee
  description: Collection of employees.
  get:
    description: Retrieve a list of employees.
    responses:
      200:
        body:
          application/json:
            #example: !include examples/employees.json
  post:
  /{id}:
    get:
